config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forumtopics
  resources :forums
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
    #,    :registrations => "registrations" }

#  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories

  #get '/topics/:id/destroy',to: 'topics#destroy'

  resources :speakerarchives

get '/users/most_lectures', to: 'users#user_with_most_lectures'
get '/users/least_lectures', to: 'users#user_with_least_lectures'
get '/speakers', to: 'welcome#displayspeakers'
get '/welcome/jsondata', to: 'welcome#jsondata'
# devise_for :users should come before resources :users


  resources :users


  resources :users, only: [:show,:index] do
    # nested resource for topics
    resources :topics, only: [:new,:show, :index]
  end


 resources :topics
 get '/topics/next/:id', to: 'topics#next'
 get '/topics/previous/:id', to: 'topics#previous'

 # resources :topics, only:[:create,:show,:index] do
 #    #nested resources for forums
 #    resources :forums, only:[:new,:show,:index]
 # end

  
  root 'welcome#index'


end

app/models/topic.rb
class Topic < ApplicationRecord

  belongs_to :user
  has_many :forums

  validates :title, presence: true
  validates :title,uniqueness: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

     before_action :currentuser

      def index
        #following if structre works when nested routes are supplied
         if params[:user_id]
           @user = User.find(params[:user_id])
           @topics = User.find(params[:user_id]).topics
          else
           @user = current_user
           @topics = current_user.topics
         end
       @topic =Topic.new
    end

      def new
        @topic = Topic.new
        @topics = current_user.topics
      end

      def create

            if params[:title]!= ""  && params[:description]!= ""  && params[:date_of_event]!= "" && params[:forum] != ""
               # @topic = Topic.find(params[])
              @topic = current_user.topics.build(topic_params)
              @topic.save
              current_user.save
              #  binding.pry
              # @forum = @topic.forums.build(name: params[:forum],location: "Saratoga");
              # @forum.save
              # @forumtopic = Forumtopic.create(forum_id: @forum.id,topic_id: @topic.id,ratings: params[:forum_rating])
              # @forumtopic.save
               if @topic.save
                #populating Join Model "Speakerarchive", which joins a user/speaker with its topics
                  # Speakerarchive.create(user_id: current_user.id,topic_id: @topic.id)
                  # Speakerarchive.save
                  #populating  Join Model "forumtopic", which joins a topic with its forum and change the value of its custom attribute  "ratings" which lies in the join table

            respond_to do |format|
               format.json { render json: @topic}# always put this on top otherwise youwill get show page as json value
                format.html { render :show } # if no JSON take to show page
            end
          end
          # redirect_to topics_path
            else
                flash[:message] = "All fields must be filled"
                redirect_to new_topic_path(@topic)
            end
          end

     def edit
       @topic = Topic.find(params[:id])
     end

      def update
        @topic = Topic.find(params[:id])
        @topic.update(topic_params)
        @topic.save
        redirect_to topic_path(@topic)
      end

      def show
    #following if is to accomodate nested routes
        if params[:user_id]
          @user = User.find(params[:user_id]);
          @topics = @user.topics
          @topic = Topic.find(params[:id]) if params[:id]
        else
          @topic = Topic.find(params[:id])
        end

      end


      def next
        nextid= params[:id].to_i+1
             while (!Topic.exists?(id: nextid))
                nextid = nextid+1
              end
              @topic = Topic.find(nextid);
        if @topic
          render json: @topic,status: 201
        end
      end

      def previous
        previousid= params[:id].to_i-1
        while (!Topic.exists?(id: previousid))
           previousid = previousid-1
         end
        @topic = Topic.find(previousid);
        if @topic
          render json: @topic,status: 201
        end
      end

      def destroy

        @topic = Topic.find(params[:id].to_i)
        # @spRecord = Speakerarchive.find_by(topic_id: @topic.id)

        @topic.delete
        # @spRecord.delete
        redirect_to topics_path
      end



  private



       def topic_params
         params.permit(:title,:description,:date_of_event,:forum)
       end

       def currentuser
         current_user
       end

  end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_edit_topic_form.html.erb
<div class="jumbotron">
  <div class="container">
<table  >
      <%= form_tag  topic_path(@topic), method: "put" do %>
          <tr><td  >Title: </td><td    ><%= text_field_tag :title,@topic.title%></td></tr><br>
          <tr><td  >Date Of Lecture: </td><td  ><%=text_field_tag :date_of_event,@topic.date_of_event,placeholder: "MM/DD/YY"%></td></tr><br>
          <tr><td  >Forum: </td><td  ><%= text_field_tag :forum,@topic.forum%></td></tr><br>
          <tr><td  >Forum Ratings(1-5): </td><td  ><%= text_field_tag :forum_rating, nil,placeholder: "Plese Rate"%></td></tr><br>
          <tr><td  >Description:</td><td  > <%= text_area_tag :description, @topic.description,cols:"25" ,rows: "6"%></td></tr><br>
          <tr><td  ></td><td  ><%= submit_tag%></td></tr></div>
    <%end%>
</table>
</div>
</div>

app/views/topics/_topic_form.html.erb
<div class="jumbotron">
  <div class="container">
<table   >
    <%#= form_for @topic do |f|%>
    <%= form_tag topics_path,class:'control',  method: 'post' do %>

          <tr><td   >Title: </td><td   ><%= text_field_tag :title %></td></tr>
          <tr><td   >Description:</td><td   > <%= text_area_tag :description%></td></tr>
          <tr><td   >Date Of Lecture: </td><td   ><%=text_field_tag :date_of_event ,nil,placeholder: "MM/DD/YY"%></td></tr>
          <tr><td   >Forum: </td><td   ><%= text_field_tag :forum%></td></tr>
          <tr><td   >How do you rate this Forum(1-10): </td><td   ><%= text_field_tag :forum_rating, nil,placeholder: "Plese Rate"%></td></tr>
          <tr><td   ></td><td   ><%= submit_tag%></td></tr>

    <%end%>
</table>
</div>
</div>

app/views/topics/edit.html.erb
<%= render 'edit_topic_form'%>

app/views/topics/index.html.erb
<div class="jumbotron">
 <% if current_user.checkallfields? %>
    <%if @topics.length >= 1%>

      <p>All Topics by <%= @user.name%>
       <ul>
         <% c=0 %>
          <% @topics.each do |topic|%>
            <br>
            <% forum = Forum.find_by(topic_id: topic.id)%>
            <li>
            <%= topic.id %>-<strong><%= topic.title%></strong>
              <p>
              <%= topic.description%>
              <br>Delivered on :<%= topic.date_of_event if topic.date_of_event%>
              <br>Forum: <b><%= topic.forum.capitalize%></b>
                (<%#= Forumtopic.find_by(topic_id: topic.id).ratings%> star rating)

                              <!-- if user is same as current user it will provide Delete and Edit option -->
                <% if @user == current_user%>
               <div style="float:left"><%= button_to "Delete",topic_path(topic),method: :delete%>
               </div>
               <div style="float:left"><%= button_to "Edit ", edit_topic_path(topic),method: :get%>
               </div>
               <% end %>
               <br>
          </li>
                <% end %>

    <%else%>

          <h4>No topics have been discussed by you so for to add one please click the link below!</h4>

    <%end%>

<% else %>


   Its highly recomended for a future speaker to create a profile!</b>

   <%= button_to "Create A Profile", edit_user_path(@user),method: :get%>
         <%= button_to "Home",users_path,method: :get%>

  <% end %>
</div>
  <div id="topicsdiv" class="jumbotron">
    <h4>You Can add a new topic for the upcoming Date in the form below!</h4>
  <table class ="noBorder">

      <%= form_tag topics_path,id: 'topicForm' do %>
  <%#= form_tag controller: "topic",action: "topicCreate", method: "post" do %>
            <tr><td class ="noBorder">Title: </td><td class ="noBorder" id="title"><%= text_field_tag :title%></td></tr>
            <tr><td class ="noBorder">Description:</td><td class ="noBorder" id="description"> <%= text_area_tag :description%></td></tr>
            <tr><td class ="noBorder">Date Of Lecture: </td><td class ="noBorder" ><%=text_field_tag :date_of_event ,nil,placeholder: "MM/DD/YY"%></td></tr>
            <tr><td class ="noBorder">Forum: </td><td class ="noBorder"><%= text_field_tag :forum%></td></tr>
            <tr><td class ="noBorder">How do you rate this Forum(1-5): </td><td class ="noBorder"><%= text_field_tag :forum_rating, nil,placeholder: "Plese Rate"%></td></tr>
            <tr><td class ="noBorder"></td><td class ="noBorder"><%= submit_tag "Add Topic",data:{disable_with: false}%></td></tr>

      <%end%>
  </table>

  <div id="messageDiv" ></div>

</div>

app/views/topics/new.html.erb
<div class="jumbotron">
  <div class="container">
<b><%= flash[:message] if flash[:message]%></b>

<%= render 'topic_form'%>
</div>
</div>

app/views/topics/show.html.erb
<div class="jumbotron">
  <div class="container">
<% if @topic %>
<div id="topic_display">
        <h3>Topic : <%= @topic.title  %></h3>
          <div id="topic_data">
             <%= @topic.description%>
                  <br>
                  <b>  <li>Date: </b> <%= @topic.date_of_event%><br>
                   <% speaker = User.find(@topic.user_id)%>
                  <b> Speaker  :</b><%= link_to speaker.name,user_path(speaker)%>

              <% if @topic.user == current_user %>
                 <%= button_to "Edit",edit_topic_path(@topic),method: :get%>
                 <%= button_to "Delete",topic_path(@topic),method: :delete%>
              <% else %>
                 <%= button_to "Home", root_path,method: :get%>
              <% end %>
          </div>
              <form>
                <input type=hidden  id ="hidden_id" value="<%=@topic.id%>">
              </form>
            </div>
<button id="previous">Previous</button>

<button id="next">Next</button>

<% else %>

        Sorry, topic id doesn't match our Record
<% end %>
</div>
</div>