config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forumtopics
  resources :forums
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
    #,    :registrations => "registrations" }

#  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories

  #get '/topics/:id/destroy',to: 'topics#destroy'

  resources :speakerarchives

get '/users/most_lectures', to: 'users#user_with_most_lectures'
get '/users/least_lectures', to: 'users#user_with_least_lectures'
get '/speakers', to: 'welcome#displayspeakers'
get '/welcome/jsondata', to: 'welcome#jsondata'
# devise_for :users should come before resources :users


  resources :users


  resources :users, only: [:show,:index] do
    # nested resource for topics
    resources :topics, only: [:new,:show, :index]
  end


 resources :topics
 get '/topics/next/:id', to: 'topics#next'
 get '/topics/previous/:id', to: 'topics#previous'

 # resources :topics, only:[:create,:show,:index] do
 #    #nested resources for forums
 #    resources :forums, only:[:new,:show,:index]
 # end

  
  root 'welcome#index'


end

app/models/speakerarchive.rb
class Speakerarchive < ApplicationRecord
  has_many :users
  has_many :topics
  has_many :categories, through: :user
end

app/models/user.rb
class User < ApplicationRecord


    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    devise :omniauthable, omniauth_providers: [:google_oauth2]
   has_many :topics
   # has_many forums, through: :topics
   # accept_nester_attributes_for :category(which has a title,description,sup_category)
   belongs_to :category, optional: true #will help save the user upon signing up other wise it give an error of category must exist

   #has_many :speakerarchives, through: :topics
 
  
 #accepts_nested_attributes_for :category, is actually equivalent to the following custom method

    def category_attributes=(category_attributes)
        c = Category.create(category_attributes)
        self.category_id = c.id

    end

    #  def is_admin?
    #    self.admin
    #  end

     def self.user_with_most_lectures
       lecture_count = 0;
       user_with_most_lectures = 2;
        User.all.each {|user| if (user.topics.count >= lecture_count)
                                lecture_count = user.topics.count
                                 user_with_most_lectures = user.id
                               else
                                  lecture_count
                              end }
                             return user_with_most_lectures
      end


      def self.user_with_least_lectures

              lecture_count = 0;
              user_with_least_lectures = 1;
        User.all.each {|user| if user.topics.count <= lecture_count
                        lecture_count = user.topics.count
                         user_with_least_lectures = user.id
                       else
                         lecture_count
                       end}
              return user_with_least_lectures

       end

  def checkallfields?
    if self.id != nil
       if  self.name ==  nil || self.education == nil || self.biography == nil|| self.website == nil
         return false
       else
         return true
       end
    end
  end
  #omniauth methods

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
      if user
        return user
      else
        registered_user = User.where(:email => access_token.info.email).first
        if registered_user
          return registered_user
        else
          user = User.create(name: data["name"],
            provider:access_token.provider,
            email: data["email"],
            uid: access_token.uid ,
            password: Devise.friendly_token[0,20],)
        end
     end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  
  private

 # def after_confirmation_path_for(resource_name, resource)
 #   redirect_to root_path
 # end

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    @users = User.all
    @user=User.first
      respond_to do |format|
         format.json { render json: @users }
         format.html { render :index } # if no JSON take to show page
      end

  end


  def new
    @user = User.new
  end

  def create
    # @user = User.create(email: params[:email])
    # @user.save
  end

  def edit
   @user = User.find(current_user.id)
  end

   def update
     @user = User.find(current_user.id)
     @user.update(user_params)
     @user.save
    redirect_to user_path(@user)
   end

    def show
      @user = User.find(params[:id])
    end


    def user_with_most_lectures
      if User.all.count > 0
          @user = User.find(User.user_with_most_lectures)
          render json: @user
      else
        redirect_to '/'
      end
    end

    def user_with_least_lectures
      if User.all.count > 0
      @user = User.find(User.user_with_least_lectures)
      render json: @user
    else
      redirect_to '/'
    end
    end



private

    def user_params

          if (params[:user][:category_id] != "")
          params.require(:user).permit(:name,:education,:biography,:website,:category_id)
          else
          params.require(:user).permit(:name,:education,:biography,:website,category_attributes: [:title,:description,:prime_category])
          end
    end

    def user_signin
      user_signed_in?
    end


end

app/views/users/_edit_user_form.html.erb
<table class ="noBorder">
    <%= form_for @user do |f|%>

          <tr><td class ="noBorder">name: </td><td class ="noBorder"><%= f.text_field :name%></td></tr>
          <tr><td class ="noBorder">Education:</td><td class ="noBorder"> <%= f.text_field :education%></td></tr>
          <tr><td class ="noBorder">Biography: </td><td class ="noBorder"><%= f.text_field :biography%></td></tr>
          <tr><td class ="noBorder">Web site: </td><td class ="noBorder"><%= f.text_field :website%></td></tr>
          <tr><td class ="noBorder">Speaker Category: </td><td class ="noBorder"><%= f.collection_select(:category_id, Category.all,:id,:title,{prompt: "Please Select A Category "})%></td></tr>

<br><%#=binding.pry%>
            <tr><td>Or add a new Category </td></tr>
            <!-- in the fields_for if a new Category is not created (Category.new) these fields will noyt appear-->
            <%= f.fields_for :category, Category.new do |category_fields| %>
                  <tr><td class ="noBorder">Title: </td><td class ="noBorder"></label><%= category_fields.text_field :title %></td></tr>
                   <tr><td class ="noBorder">Description:</td><td class ="noBorder"><%= category_fields.text_field :description %></td></tr>
                   <tr><td class ="noBorder">Prime Category: </td><td class ="noBorder"><%= category_fields.text_field :prime_category  %></td></tr>
            <% end %>
          </td></tr>
          <tr><td class ="noBorder"></td><td class ="noBorder"><%= f.submit "Create Profile"%></td></tr>

    <%end%>
</table>

app/views/users/_user_form.html.erb
<table class ="noBorder">
    <%= form_for @user do |f|%>

          <tr><td class ="noBorder">name: </td><td class ="noBorder"><%= f.text_field :name%></td></tr>
          <tr><td class ="noBorder">Education:</td><td class ="noBorder"> <%= f.text_field :education%></td></tr>
          <tr><td class ="noBorder">Biography: </td><td class ="noBorder"><%= f.text_field :biography%></td></tr>
          <tr><td class ="noBorder">Web site: </td><td class ="noBorder"><%= f.text_field :website%></td></tr>
          <tr><td class ="noBorder">Speaker Category: </td><td class ="noBorder"><%= f.collection_select(:category_ids, Category.all,:id,:name,{prompt: "Please Select A Category "})%></td></tr>
          <tr><td class ="noBorder">New Category: </td><td class ="noBorder">
          <%= f.fields_for :categories, @user.categories.build do |categories_fields| %>
           <%= categories_fields.text_field :name %>
           <% end %><%#= f.text_field :new_category})%></td></tr>
          <tr><td class ="noBorder"></td><td class ="noBorder"><%= f.submit "Create Your Profile"%></td></tr>

    <%end%>
</table>

app/views/users/edit.html.erb
<div class="jumbotron">
  <div class="container">
<%= render 'edit_user_form'%>
</div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">
<H1>Speakers</h1>
  <% User.all.each do |user| %>
  <table>
   <tr><td><%= user.name %></td>
   <td>&nbsp;&nbsp;&nbsp;
         <% if current_user && user.id == current_user.id %>
         <%= link_to "More About Speaker", user_path(user),method: :get%>/
         <%= link_to "Edit", edit_user_path(user),method: :get%>
         <% else %>
         <%= link_to "More About Speaker", user_path(user),method: :get%>
         <% end %>
    </td>
   <%end %>
 </table>
</div>

app/views/users/new.html.erb
<%= render "user_form"%>
<%#= render "signup_form"%>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="container">
    <table class ="noBorder">

      <% if @user &&  @user.checkallfields? %>

      <h3> <%= @user.name.capitalize%></h3>

       <% category = Category.find(@user.category_id)  %>

         <tr><td class ="noBorder">Education:</td><td class ="noBorder"> <%= @user.education if @user.education%></td></tr>

         <tr><td class ="noBorder">Biography: </td><td class ="noBorder"><%= @user.biography if @user.biography%></td></tr>

         <tr><td class ="noBorder">Web site: </td><td class ="noBorder"><%=link_to @user.website,"http://#{@user.website}"%></td></tr>

      <% if category  != nil%>
         <tr><td class ="noBorder">Speaker Category:&nbsp;&nbsp; </td><td class ="noBorde@use."><%= category.title if category%><b></b></td></tr>
             <tr><td class ="noBorder"> Category Description:&nbsp;&nbsp; </td><td class ="noBorde@use."><%= category.description if category%><b></b></td></tr>
                      <tr><td class ="noBorder">Prime Category:&nbsp;&nbsp; </td><td class ="noBorde@use."><%= category.prime_category if category%><b></b></td></tr>
              <% else %>
              <%= button_to "Add Category",new_category_path %>
              <% end %>
         <br>
         <tr>

           <% if user_signed_in? && @user.id == current_user.id %>
              <%= link_to "New Topic",new_user_topic_path(@user)%>  <!-- this link is using nested routes-->


          <% end %>

      <% else %>
         Its highly recomended for a future speaker to create a profile!</b>

        <tr> <td  class ="noBorder"></td><td class ="noBorder"> <%= button_to "Create A Profile", edit_user_path,method: :get%></td>
             <td class ="noBorder">   <%= button_to "Home",user_path,method: :get%></td>
            <td class ="noBorder"></td>
        </tr>
      <% end%>
      </table>
    </div>
</div>

app/views/users/user_with_least_lectures.html.erb
<h2>Welcome,</h2>
<% if @user.name == nil%>
<strong>Speaker Profile under process!</strong><br>
<% name = "Undefined"%>
<% else %>
<% name = @user.name %>
<% end %>

Speaker with least lectures is <strong> <%=link_to  name,user_path(@user)%></strong>,with <%= @user.topics.count%>
<%= link_to "Topics",user_topics_path(@user)%>

app/views/users/user_with_most_lectures.html.erb
<h2>Welcome,</h2>
Speaker with most lectures is <strong> <%=link_to  @user.name.capitalize(),user_path(@user)%></strong>,with <%= @user.topics.count%>
<%= link_to "Topics",user_topics_path(@user)%>