config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :forumtopics
  resources :forums
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
    #,    :registrations => "registrations" }

#  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories

  #get '/topics/:id/destroy',to: 'topics#destroy'

  resources :speakerarchives

get '/users/most_lectures', to: 'users#user_with_most_lectures'
get '/users/least_lectures', to: 'users#user_with_least_lectures'
get '/speakers', to: 'welcome#displayspeakers'
get '/welcome/jsondata', to: 'welcome#jsondata'
# devise_for :users should come before resources :users


  resources :users


  resources :users, only: [:show,:index] do
    # nested resource for topics
    resources :topics, only: [:new,:show, :index]
  end


 resources :topics
 get '/topics/next/:id', to: 'topics#next'
 get '/topics/previous/:id', to: 'topics#previous'

 # resources :topics, only:[:create,:show,:index] do
 #    #nested resources for forums
 #    resources :forums, only:[:new,:show,:index]
 # end

  
  root 'welcome#index'


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :users
  has_many :speakerarchives, through: :users
  validates :title, uniqueness: true
  validates :title, presence: true
end

app/models/forum.rb
class Forum < ApplicationRecord

   has_many :topics
   has_many :users, through: :topics

   def self.find_or_create_by(name)

       forum = Forum.find_by(name: name)
      if forum
         return forum
       else
         forum = Forum.create(name:name,location:"San Jose",number_of_speakers: 100,audience: 2000)
       end
       return forum
    end

end

app/models/forumtopic.rb
class Forumtopic < ApplicationRecord
  belongs_to :forum
  belongs_to :topic
  has_many :users, through: :topic
end

app/models/speakerarchive.rb
class Speakerarchive < ApplicationRecord
  has_many :users
  has_many :topics
  has_many :categories, through: :user
end

app/models/topic.rb
class Topic < ApplicationRecord

  belongs_to :user
  has_many :forums

  validates :title, presence: true
  validates :title,uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord


    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    devise :omniauthable, omniauth_providers: [:google_oauth2]
   has_many :topics
   # has_many forums, through: :topics
   # accept_nester_attributes_for :category(which has a title,description,sup_category)
   belongs_to :category, optional: true #will help save the user upon signing up other wise it give an error of category must exist

   #has_many :speakerarchives, through: :topics
 
  
 #accepts_nested_attributes_for :category, is actually equivalent to the following custom method

    def category_attributes=(category_attributes)
        c = Category.create(category_attributes)
        self.category_id = c.id

    end

    #  def is_admin?
    #    self.admin
    #  end

     def self.user_with_most_lectures
       lecture_count = 0;
       user_with_most_lectures = 2;
        User.all.each {|user| if (user.topics.count >= lecture_count)
                                lecture_count = user.topics.count
                                 user_with_most_lectures = user.id
                               else
                                  lecture_count
                              end }
                             return user_with_most_lectures
      end


      def self.user_with_least_lectures

              lecture_count = 0;
              user_with_least_lectures = 1;
        User.all.each {|user| if user.topics.count <= lecture_count
                        lecture_count = user.topics.count
                         user_with_least_lectures = user.id
                       else
                         lecture_count
                       end}
              return user_with_least_lectures

       end

  def checkallfields?
    if self.id != nil
       if  self.name ==  nil || self.education == nil || self.biography == nil|| self.website == nil
         return false
       else
         return true
       end
    end
  end
  #omniauth methods

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
      if user
        return user
      else
        registered_user = User.where(:email => access_token.info.email).first
        if registered_user
          return registered_user
        else
          user = User.create(name: data["name"],
            provider:access_token.provider,
            email: data["email"],
            uid: access_token.uid ,
            password: Devise.friendly_token[0,20],)
        end
     end
  end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController

def index
 @forums = Forum.all
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



  def index
    @users = User.all
    @user=User.first
      respond_to do |format|
         format.json { render json: @users }
         format.html { render :index } # if no JSON take to show page
      end

  end


  def new
    @user = User.new
  end

  def create
    # @user = User.create(email: params[:email])
    # @user.save
  end

  def edit
   @user = User.find(current_user.id)
  end

   def update
     @user = User.find(current_user.id)
     @user.update(user_params)
     @user.save
    redirect_to user_path(@user)
   end

    def show
      @user = User.find(params[:id])
    end


    def user_with_most_lectures
      if User.all.count > 0
          @user = User.find(User.user_with_most_lectures)
          render json: @user
      else
        redirect_to '/'
      end
    end

    def user_with_least_lectures
      if User.all.count > 0
      @user = User.find(User.user_with_least_lectures)
      render json: @user
    else
      redirect_to '/'
    end
    end



private

    def user_params

          if (params[:user][:category_id] != "")
          params.require(:user).permit(:name,:education,:biography,:website,:category_id)
          else
          params.require(:user).permit(:name,:education,:biography,:website,category_attributes: [:title,:description,:prime_category])
          end
    end

    def user_signin
      user_signed_in?
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end

    def displayspeakers
    end

    # def jsondata
    #   @users = User.all
    #
    #
    #       #binding.pry
    #  #render json: @user
    #     respond_to do |format|
    #          format.json { render json: @users.to_json(include: [:topic]) }
    #          format.html { render :displayspeakers } # if no JSON take to show page
    #       end
    #
    # end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/forum_helper.rb
module ForumHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/forumtopics_helper.rb
module ForumtopicsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/regitrations_helper.rb
module RegitrationsHelper
end

app/helpers/speaker_helper.rb
module SpeakerHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/displayspeakers.html.erb
<% if current_user %>
<p><b>Hi <%= current_user.name if current_user.name%>!</b> You Can Manage All Speakers Data Here</p>

<button id="speakerdata" >All Speakers</button>
<button id="speakers_mostLectures">Mostly Heard</button>
<button id="speakers_leastLectures">Least Heard</button>
<% else%>
 <p>Please Sign In, Only members can see this page</p>
 <a class="nav-link " href="/users/sign_in">Sign In </a>
 <% end%>

 <div id="displaymode" ></div>
 </div>

app/views/welcome/index.html.erb
<div class="alignpages">
  <div class="center">
<main role="main">

      <!-- Marketing messaging and featurettes-->

      <!--================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

        <!-- Three columns of text below the carousel -->
  <div class="welcome-user">Hi <%=  current_user != nil ? current_user.name: "Future User"%>!</div>
        <div class="container marketing">


        <div class="row">

          <div class="col-lg-4">


            <img class="rounded-circle" src="assets/round1.jpeg" alt="Generic placeholder image" width="140" height="140">
            <h2 class="headings-style">Learn About Us In Few Minutes</h2>
            <p>CSIX CONNECT helps individuals in career transition to significantly improve their job search success through education, in-person networking and mutual support.   In today’s job market, more than 80 per cent of jobs obtained result from successful networking.</p>

            <p><div class="btn btn-secondary popup"  onclick="myFunction()">View details »
                   <span class="popuptext" id="myPopup" >
                      <div class="link-class"> <a href="#">Link 1</a></div>
                                  </span>
            </div>
          </p>


          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="assets/round2.png" alt="About you image" width="140" height="140" align="middle">
            <h2 class="headings-style">Tell Us About Yourself</h2>
            <p>Please tell us about you. What makes you a unique speaker who can change people's life</p>
            <p><button class="btn btn-secondary popup"  onclick="myFunction2()">View details »
                   <div class="popuptext popLayout" id="myPopup2" >
                  <div class="link-class"><a href="#"> Link 2</a></div>
                  </div>
            </button>
          </div>
          </p><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="assets/round3.png" alt="Future Speaker" width="140" height="140">
            <h2 class="headings-style">Become A Speaker!</h2>

            <p>CSIX is built on the belief that networking is most effective when done face-to-face. Therefore, to join CSIX you must attend a meeting and sign up in person. Membership is free. CSIX membership provides access to a vast array of job listings and job search resources via other members, the CSIX CONNECT Yahoo! group.</p>
            <p><button class="btn btn-secondary popup"  onclick="myFunction3()">View details »
                   <span class="popuptext" id="myPopup3" >
                  <div class="link-class"><a href="#">Link 3</a></div>
                  <span>
            </button></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
      <div class="container">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/y_6aZX35x28" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
          </div>

          </body>
        </html>


        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div>
    </div>


      <!-- /.container -->
      <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="./index_files/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
      <script src="./index_files/popper.min.js"></script>
      <script src="./index_files/bootstrap.min.js"></script>
      <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
      <script src="./index_files/holder.min.js"></script>


    <svg xmlns="http://www.w3.org/2000/svg" width="500" height="500" viewBox="0 0 500 500" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="25" style="font-weight:bold;font-size:25pt;font-family:Arial, Helvetica, Open Sans, sans-serif">500x500</text></svg></body></html>

app/views/welcome/index1.html.erb
<div class="et_pb_text_inner">

<h2 style="text-align: center;">Welcome to CSIX</h2>
<p>CSIX CONNECT helps individuals in career transition to significantly improve their job search success through education, in-person networking and mutual support.   In today’s job market, more than 80 per cent of jobs obtained result from successful networking. CSIX CONNECT provides the means to tap into and leverage the power of a network that is already more than 7000 members strong.</p>
<hr />
<img src="assets/images/logo.png">


<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank"><input name="cmd" type="hidden" value="_s-xclick" /><input name="hosted_button_id" type="hidden" value="9WDRN6M2HWQJQ" /><style type='text/css'></style><span id='csmi-ba1a50fbf9f8ce2507c4b44f8a16b7ae' class='csmi csmi-bid-1 csmi-GreatNonProfits'> <script type="text/javascript">
gnp_request = {"slug" : "csix-connect", "color-set" : 1 , "campaign" : 54};
</script>
<style> div.gnp_trb { visibility:hidden; } </style>
<script src="https://greatnonprofits.org/js/api/badge_toprated.js" type="text/javascript"> </script>

<div class="gnp_trb" id="gnp_trb">
<a href="http://greatnonprofits.org/org/csix-connect">
<img src="//cdn.greatnonprofits.org//img/2015-top-rated-awards-badge-embed.png?id=360161" alt="CSIX CONNECT Nonprofit Overview and Reviews on GreatNonprofits" title="2015 Top-rated nonprofits and charities" />
</a>
</div></span> <input alt="PayPal - The safer, easier way to pay online!" name="submit" src="http://csix.org/wp-content/uploads/2014/11/x-click-but21.gif" type="image" />              </form>

</div>
</div> <!-- .et_pb_text -->
</div> <!-- .et_pb_column --><div class="et_pb_column et_pb_column_1_2  et_pb_column_1">
<div class="et_pb_text et_pb_module et_pb_bg_layout_dark et_pb_text_align_left  et_pb_text_1">
<p><a href="https://www.linkedin.com/company/csix-connect"
 target="_blank">
 <img class="alignnone wp-image-446 csix-social-logo" src="http://csix.org/wp-content/uploads/2015/03/CSIX-LinkedIn.png" alt="CSIX-LinkedIn" /></a>
  <a href="http://www.meetup.cofacebookm/CSIX-Connect/" target="_blank">
    <img class="alignnone  wp-image-445 csix-social-logo" src="http://csix.org/wp-content/uploads/2015/03/meetuplogo.png" alt="meetuplogo" /></a>
       <a href="https://www.facebook.com/csixconnect" target="_blank">
         <img class="alignnone  wp-image-444 csix-social-logo" src="http://csix.org/wp-content/uploads/2015/03/FB_FindUsOnFacebook-320-300x77.png" alt="facebooklogo" width= 150 height=200 /></a></p>
</div>
<div>
  <%= link_to "Forums",forums_path%>
  /<%=link_to "All Speakers",users_path%>/<%=link_to "Popular Speaker", "/users/most_lectures"%><br>
</div>